### ISSUE TITLE
Warehouse Migration Role Error

### ISSUE THREAD

**Issue by senorlocksmith** [greenriver/hmis-warehouse#1483]
Running in Windows 10 x64 WSL2 Ubuntu 20LTS I am getting a migration error in the warehouse section regarding a role 'bi'. I see the role in the migration but cannot figure out what is causing this issue as both PostgreSQL and Postgis are installed and working. Any help would be appreciated greatly. 

`== 20200701192839 NewReportingViews: migrating ================================
-- CREATE OR REPLACE VIEW "bi_Organization" AS SELECT "Organization"."OrganizationID", "Organization"."OrganizationName", "Organization"."VictimServicesProvider", "Organization"."OrganizationCommonName", "Organization"."DateCreated", "Organization"."DateUpdated", "Organization"."UserID", "Organization"."DateDeleted", "Organization"."ExportID" FROM "Organization" WHERE "Organization"."DateDeleted" IS NULL
   -> 0.0050s
-- GRANT SELECT ON "bi_Organization" TO bi
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedObject: ERROR:  role "bi" does not exist
: GRANT SELECT ON "bi_Organization" TO bi
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/rack-mini-profiler-2.3.0/lib/patches/db/pg.rb:110:in `exec'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/rack-mini-profiler-2.3.0/lib/patches/db/pg.rb:110:in `async_exec'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `synchronize'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:37:in `block in safe_create_view'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:840:in `block in say_with_time'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:840:in `say_with_time'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:36:in `safe_create_view'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:160:in `non_client_view'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:70:in `up'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:817:in `exec_migration'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:797:in `block in migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:796:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:977:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:212:in `transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `ddl_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `each'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `block in migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1036:in `up'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1011:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/home/senorlocksmith/code/hmis-warehouse/lib/tasks/warehouse.rake:24:in `block (3 levels) in <main>'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  role "bi" does not exist
: GRANT SELECT ON "bi_Organization" TO bi
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/rack-mini-profiler-2.3.0/lib/patches/db/pg.rb:110:in `exec'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/rack-mini-profiler-2.3.0/lib/patches/db/pg.rb:110:in `async_exec'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `synchronize'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:37:in `block in safe_create_view'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:840:in `block in say_with_time'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:840:in `say_with_time'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:36:in `safe_create_view'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:160:in `non_client_view'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:70:in `up'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:817:in `exec_migration'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:797:in `block in migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:796:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:977:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:212:in `transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `ddl_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `each'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `block in migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1036:in `up'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1011:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/home/senorlocksmith/code/hmis-warehouse/lib/tasks/warehouse.rake:24:in `block (3 levels) in <main>'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
PG::UndefinedObject: ERROR:  role "bi" does not exist
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/rack-mini-profiler-2.3.0/lib/patches/db/pg.rb:110:in `exec'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/rack-mini-profiler-2.3.0/lib/patches/db/pg.rb:110:in `async_exec'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `synchronize'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:37:in `block in safe_create_view'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:840:in `block in say_with_time'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:840:in `say_with_time'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:36:in `safe_create_view'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:160:in `non_client_view'
/home/senorlocksmith/code/hmis-warehouse/db/warehouse/migrate/20200701192839_new_reporting_views.rb:70:in `up'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:817:in `exec_migration'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:797:in `block in migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:796:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:977:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:212:in `transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `ddl_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `each'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `block in migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1036:in `up'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1011:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/activerecord-5.2.4.5/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/home/senorlocksmith/code/hmis-warehouse/lib/tasks/warehouse.rake:24:in `block (3 levels) in <main>'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/home/senorlocksmith/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Last command failed. Aborting.`

**Comment by eanders** [comment]
@senorlocksmith,  thanks for opening the issue.  We actually ran into this today when setting up a new developer.  Looks like we have some migration rot.  The quickest way around this would be to try and get the warehouse database setup with schema load instead of migrate.
```
RAILS_ENV=development rake warehouse:db:drop
RAILS_ENV=development rake warehouse:db:create
RAILS_ENV=development rake warehouse:db:schema:load
```

If that doesn't work, I believe it's safe to skip all of the migrations that fail (just stick a `return` at the top of the up or change method in each after they fail and try again.)

`bin/setup` _should_ have run a schema load but sometimes gets confused and attempts to run the migrations.
Let us know how it goes!

**Comment by senorlocksmith** [comment]
@eanders Thank you for the quick reply. I did do this and got much of the databases built out. Because many of the databases are linked I ended up having to create most of them manually each. However after getting the databases created and schema loaded the seeding still does not work. Displaying error below. 

I fear I might be missing another element. I examined the bin/setup and bin/db_prep and ran much of the rails console elements to see where it stops and now its around seeding giving this error:

`ActiveRecord::RecordInvalid: Validation failed: Agency can't be blank`

Additionally for anyone else reading the 

`RAILS_ENV=development rake warehouse:db:schema_load` 

should be

`RAILS_ENV=development rake warehouse:db:schema:load`

Since I can assume the seeding takes care of loading one admin user and I cannot access a register prompt its hard to get in and add a user. Let me know your thoughts. Thanks again.

**Comment by eanders** [comment]
@senorlocksmith , thanks for correcting the schema load syntax, I've updated my comment above.  I've also pushed a fix to `setup_fake_user` which should resolve your "Agency can't be blank" validation issue.

Running `rake db:seed` should now create a sample user and echo the password.  Alternatively, you could step through the lines [found here](https://github.com/greenriver/hmis-warehouse/blob/797401809d09cab522c76d16e175bcad64d0fc10/db/seeds.rb#L3) manually in a rails console.

**Comment by eanders** [comment]
@senorlocksmith please re-open if you continue to have issues.  This code should be fixed.
