### ISSUE TITLE
NoMethodError: undefined method `merge' for nil:NilClass

### ISSUE THREAD

**Issue by pocketfishy** [greenriver/hmis-warehouse#2819]
Hi,
I am experiencing the following error when running bin/setup. My gemfile and NPM dependencies appear to be installing successfully, but when preparing the database I receive the follow error: `NoMethodError: undefined method `merge' for nil:NilClass`. Here is the output of bin/setup:

`== Installing dependencies ==
The Gemfile's dependencies are satisfied
== Installing NPM dependencies ==
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.38s.

== Preparing Database ==
rake aborted!
NoMethodError: undefined method `merge' for nil:NilClass
/home/ubuntu/hmis-warehouse/config/environments/development.rb:38:in `block in <main>'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/railtie.rb:234:in `instance_eval'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/railtie.rb:234:in `configure'
/home/ubuntu/hmis-warehouse/config/environments/development.rb:3:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:332:in `require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/engine.rb:570:in `each'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/engine.rb:570:in `block in <class:Engine>'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/initializable.rb:32:in `instance_exec'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/initializable.rb:32:in `run'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/initializable.rb:50:in `each'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/initializable.rb:60:in `run_initializers'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/application.rb:391:in `initialize!'
/home/ubuntu/hmis-warehouse/config/environment.rb:5:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:332:in `require'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/application.rb:367:in `require_environment!'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/railties-6.1.7.1/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/sentry-ruby-5.7.0/lib/sentry/rake.rb:24:in `execute'
/home/ubuntu/.rvm/gems/ruby-2.7.6/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => db:create:primary => db:load_config => environment
(See full trace by running task with --trace)
Last command failed. Aborting.

== Setting up test databases
Dropped database 'test_openpath_app'
Dropped database 'test_openpath_warehouse'
Dropped database 'test_openpath_health'
Dropped database 'test_openpath_reporting'
Dropped database 'test_openpath_cas'
Created database 'test_openpath_app'`

**Comment by eanders** [comment]
That looks like you don't have a redis server setup.  If you `touch tmp/caching-dev.txt` it'll setup a memory store instead.  
Alternatively, you can specify the Redis info in `.env.local` You'll need to specify the variables used in `config/cache_store.yml`

**Comment by pocketfishy** [comment]
Thank you, @eanders. This resolved my issue

**Comment by eanders** [comment]
Great!  Let us know if anything else comes up
