### ISSUE TITLE
Enrollment remaining to process

### ISSUE THREAD

**Issue by pocketfishy** [greenriver/hmis-warehouse#3126]
Hi there,
I have been able to set up the Open Path application and upload the HMIS CSV in a new data source. The import runs successfully, but when returning to the data source page, it says "Enrollments remaining to process: 131". The number is always the total number of enrollments minus 1. I read in the wiki that it says, "Full processing of an upload, where client records and reports reflect the new data, may take up to 24 hours." However, it has been more than 24 hours and the number of remaining enrollments left to process is still the same, and there a no short or long running background jobs. So my question is: can I somehow force the remaining enrollments to be processed? Or is there a better way that I can remedy this situation?
Thank you!

![image](https://github.com/greenriver/hmis-warehouse/assets/110262695/c2bc6eb3-6d5e-487f-ac3c-218b65cb6caf)
![image](https://github.com/greenriver/hmis-warehouse/assets/110262695/cad8595c-56ec-4c9d-ad98-ebab7fdca963)
![image](https://github.com/greenriver/hmis-warehouse/assets/110262695/474adce8-43e4-4d4d-b885-2585c7c8d11d)

**Comment by eanders** [comment]
Good question.  Running the importer should also do the post processing.  You can always run `rails grda_warehouse:daily` that's kind of a sledgehammer that should take care of most background jobs and which in production runs nightly.  When you run that, you'll need to make sure you have at least one (maybe two job workers running to process queued jobs.)  You can kick those off with `rails jobs:work`.

**Comment by pocketfishy** [comment]
Thanks for the quick response, @eanders. I tried running the command you suggested and I am receiving the following error message:
`ubuntu@ip-172-31-31-96:~/hmis-warehouse$ rails grda_warehouse:daily
I, [2023-06-07T18:52:35.568280 #3512]  INFO -- : Revoked expired client consent if appropriate
I, [2023-06-07T18:52:35.642480 #3512]  INFO -- : Set client consent if appropriate
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "project_clients" does not exist
LINE 8:  WHERE a.attrelid = '"project_clients"'::regclass
                            ^
/home/ubuntu/hmis-warehouse/app/models/grda_warehouse/tasks/push_clients_to_cas.rb:33:in `block in sync!'
/home/ubuntu/hmis-warehouse/app/models/grda_warehouse/tasks/push_clients_to_cas.rb:30:in `sync!'
/home/ubuntu/hmis-warehouse/app/jobs/importing/run_daily_imports_job.rb:249:in `sync_with_cas'
/home/ubuntu/hmis-warehouse/app/jobs/importing/run_daily_imports_job.rb:49:in `block in perform'
/home/ubuntu/hmis-warehouse/app/jobs/importing/run_daily_imports_job.rb:31:in `perform'
/home/ubuntu/hmis-warehouse/lib/tasks/grda_warehouse.rake:250:in `block (2 levels) in <main>'

Caused by:
PG::UndefinedTable: ERROR:  relation "project_clients" does not exist
LINE 8:  WHERE a.attrelid = '"project_clients"'::regclass
                            ^
/home/ubuntu/hmis-warehouse/app/models/grda_warehouse/tasks/push_clients_to_cas.rb:33:in `block in sync!'
/home/ubuntu/hmis-warehouse/app/models/grda_warehouse/tasks/push_clients_to_cas.rb:30:in `sync!'
/home/ubuntu/hmis-warehouse/app/jobs/importing/run_daily_imports_job.rb:249:in `sync_with_cas'
/home/ubuntu/hmis-warehouse/app/jobs/importing/run_daily_imports_job.rb:49:in `block in perform'
/home/ubuntu/hmis-warehouse/app/jobs/importing/run_daily_imports_job.rb:31:in `perform'
/home/ubuntu/hmis-warehouse/lib/tasks/grda_warehouse.rake:250:in `block (2 levels) in <main>'
Tasks: TOP => grda_warehouse:daily
(See full trace by running task with --trace)`

Could this be occurring since I am still using the development environment? As always your help is much appreciated.

**Comment by eanders** [comment]
If you set `DATABASE_CAS_DB` to a blank string something like `DATABASE_CAS_DB=` in the .env file, does it get through that?  It sounds like you haven't setup [CAS](https://github.com/greenriver/boston-cas/), which is fine, but the warehouse needs to be told the CAS database isn't fully setup.

**Comment by pocketfishy** [comment]
Amazing, that worked!! Thank you, Elliot
