### ISSUE TITLE
A value is required for NativeHIPacific

### ISSUE THREAD

**Issue by pocketfishy** [greenriver/hmis-warehouse#3173]
Hello,
I'm running into an issue with the HMIS CSV Importer. Despite my Client.csv file having valid values for the column, "NativeHIPacific", it doesn't appear to recognize them. Each client in the import returns a validation error saying, "A value is required for NativeHIPacific". The rest of the race & ethnicity fields all import without issue.
Any guidance would be much appreciated!

[Client_errors.xlsx](https://github.com/greenriver/hmis-warehouse/files/11776841/Client_errors.xlsx)

**Comment by eanders** [comment]
Hm, the sheet you attached seems to have blanks for that column.  Can you double check the header capitalization/spelling in your Client.csv?  I'm guessing there's a typo there.  I'm happy to look at a Client.csv file if you want to post one with just one client row and faked name, SSN, and DOB.

**Comment by pocketfishy** [comment]
Thanks @eanders, here is the Client.csv file that I am using
[Client.csv](https://github.com/greenriver/hmis-warehouse/files/11777127/Client.csv)

**Comment by eanders** [comment]
Ok, so this is just a guess, but the warehouse doesn't yet know how to handle encrypted/hashed names and SSNs.  The names should be ok, those allow up to 50 characters, but the SSN is limited to 9 characters.  I don't know why it would be upset about NativeHIPacific and not the SSN column, but everything else looks reasonable.  

If you want to pre-validate the import, you can unzip it to somewhere like `var/validate_import/` and then run
```
r = GrdaWarehouse::Tasks::HmisCsvValidator.new('var/validate_import/')
r.run!
r.errors
```
And it should give you a sense of if the warehouse is going to have problems with the import.  (It's not 100% of the checks, but it's pretty good.)

**Comment by pocketfishy** [comment]
So I just tried replacing First Name, Middle Name, Last Name, and SSN (all of the encrypted fields) with placeholder values, but unfortunately I'm still getting the same validation error on NativeHIPacific

**Comment by eanders** [comment]
Does the validator give you any useful information?

**Comment by pocketfishy** [comment]
Not really, the only thing it says is that NativeHIPacific is blank, but
when I look at the column in my Client.csv it has values there, so I’m
kinda at a loss

**Comment by eanders** [comment]
@pocketfishy I just ran the file you sent through the validator and I'm only seeing errors on the SSN length.  If I move the data from the SSN column, it doesn't have any errors.  Any chance you have a clean CSV, but in the zip file something is different?

**Comment by pocketfishy** [comment]
@eanders Thank you for your suggestions. The csv file was extracted from the zip, so they should be identical. I tried it again with blank values for FirstName, MiddleName, LastName, and SSN, however I still received the same validation error for NativeHIPacific in Client.csv. I am also getting a validation error stating that 'A value is required for VictimServiceProvider' in Organization.csv, despite there being a value of 1. I'm wondering if you have any other suggestions? Are there any configuration options, either at the user level or at the data source level that could be affecting this? I feel like I'm so close but these 2 validation errors are preventing me from being able to generate the ESG CAPER. 
Thank you,

**Comment by eanders** [comment]
There aren't any configuration options around the import setup.  I guess I'd need to see the full zip file and try to load it locally to see if I can reproduce the issue.  It's very odd that it's erroring partway through the file, almost like there's an un-quoted comma in there somewhere.

**Comment by pocketfishy** [comment]
Here is the complete zip file I am importing. If you could try to replicate the error that would be much appreciated!
[HMIS CSV (24).zip](https://github.com/greenriver/hmis-warehouse/files/11872675/HMIS.CSV.24.zip)

**Comment by eanders** [comment]
Hmm, so I'm seeing the same validation error, but the import succeeds.  I wonder if this is a bug where if there are no `1`s in the column, ruby gets confused.  That said, this isn't an error that blocks importing, just a validation flag.  So you should have the data available once the processing has finished.  Do you see something similar to this when you look at your import log? Or are you seeing errors in other columns?
<img width="1497" alt="Screenshot 2023-06-26 at 3 52 39 PM" src="https://github.com/greenriver/hmis-warehouse/assets/1346876/5cfd1350-2118-4d30-975c-1199856a166f">

**Comment by pocketfishy** [comment]
Yes I am getting the same results as you show in the screenshot. The import succeeds and the data is there, however the NativeHIPacific and VictimServiceProvider fields are blank. These fields are required to have data in them by HUD, so when I go to generate the CAPER, it produces inaccurate results. As a condition of the grant we are required to collect data on race. For the 6 people who have a 1 in NativeHIPacific it shows them as having no data collected, which would give us a lower ranking and make us less likely to receive the grant in the future.

**Comment by eanders** [comment]
Ah, that makes sense.  I'll take a further look now that I can duplicate the issue locally.

**Comment by eanders** [comment]
I was able to track down what's causing the issue. Export.csv is missing a value in CSVVersion.   The importer tries to be smart and if there's no CSVVersion column, or no value for it, it assumes it's in the 2020 spec since that was introduced in FY2022.   This causes the importer to "migrate" the data shape, which is breaking the NativeHIPacific and VictimServiceProvider fields.  

You should put something like `FY2022` in the CSVVersion cell in Export.csv and you should be good to go.
It also appears you have extra commas at the end of each line in Disabilities.cs and Services.csv which may break things for those files.

**Comment by pocketfishy** [comment]
Amazing! Thank you so much, @eanders. That fixed the issue!!

**Comment by eanders** [comment]
Phew.  Glad that was it!
