### ISSUE TITLE
Length of hashed SSN field creates data quality error when running CAPER report

### ISSUE THREAD

**Issue by pocketfishy** [greenriver/hmis-warehouse#3227]
Hi,
I noticed that the SSN field is enforcing a length of 9 digits. This works ok when importing unencypted data. However it creates a data quality error when running a CAPER report with a hash status not equal to 'Unhashed'. The [HMIS CSV Specification Manual](https://hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.3.pdf) says that the SSN field should be 68 characters long to allow for last four digits of the unencrypted SSN + the 64 character long hash value

![image](https://github.com/greenriver/hmis-warehouse/assets/110262695/a04ff3c0-4b0c-4e78-ad47-870275a3893d)

For security reasons, I do not want to upload unencrypted names and SSNs. Would it be possible to change the length of the SSN field to be 68 characters?

Thank you!

**Comment by eanders** [comment]
@pocketfishy , this is a known divergence from the CSV spec, and I believe we plan to adjust to handle it as part of the 2024 spec changes.  Feel free to simply increase the size of the database column in your installation.  It's possible the importer will complain, but I _think_ those are just warnings/validations, not errors, so the data should get in.  I'm not sure how the CAPER will handle hashed SSNs, I don't believe the programming specifications are setup to handle that.

**Comment by pocketfishy** [comment]
Got it - thank you!
