### ISSUE TITLE
FY 2024 HMIS Data Standards

### ISSUE THREAD

**Issue by pocketfishy** [greenriver/hmis-warehouse#3478]
Hi there,
I saw that beginning on October 1, 2023, HUD will begin requiring that all HMISs use the 2024 data standards. I am getting ready to run a HUD APR report, and I'm only seeing options to run the FY 2022 and FY 2023 versions of the report. Is there currently a timeline for when the FY 2024 version will be available?
Thank you!

![image](https://github.com/greenriver/hmis-warehouse/assets/110262695/8e5d2baa-905c-4da2-8559-e3231d7b348a)

**Comment by eanders** [comment]
We are in the process of making updates for the FY 2024 changes now.  Some are already merged into `release-86` others that can't be deployed before 10/1 [are on this PR](https://github.com/greenriver/hmis-warehouse/pull/3398).  HUD report updates will be coming shortly after 10/1.  The APR/CAPER changes are first on our schedule with the goal of releasing them within the first week or two of October.

**Comment by pocketfishy** [comment]
That's great, @eanders. Thanks for letting me know
