### ISSUE TITLE
Some URLs throwing 404 error

### ISSUE THREAD

**Issue by pocketfishy** [greenriver/hmis-warehouse#3706]
Hi,
I'm noticing some unusual behavior regarding the URLs for data sources. For example, the first data source I created appears to have been created successfully, but when I went to view it in order to upload my .zip file, it gave me a 404 error for the following url: http://ec2-54-202-194-225.us-west-2.compute.amazonaws.com/data_sources/==MqS%2FtGjkW2z+9WYiT3LMCQ== (notice the %2F in the URL)
I then tried creating another data source, and was able to view it with no problems: http://ec2-54-202-194-225.us-west-2.compute.amazonaws.com/data_sources/==uYBa8oeWryDHZB8aYLEN8g== (no %2F in the URL)
I was able to upload the .zip file for this second data source, however it did throw a validation error. When I went to examine the validation error, it gave me another 404 with the following url (again containing %2F): http://ec2-54-202-194-225.us-west-2.compute.amazonaws.com/hmis_csv_importer/importer_validations/==MqS%2FtGjkW2z+9WYiT3LMCQ==/Client

I'm wondering if rails is creating some kind of encoded id, which happens to contain %2F, which apache is interpreting as a forward slash? 
Thank you,
![image](https://github.com/greenriver/hmis-warehouse/assets/110262695/9aa2b570-6af7-4d31-bf49-7ada0aa2fcff)
![image](https://github.com/greenriver/hmis-warehouse/assets/110262695/4faea13e-eb15-4bf0-a83f-058ec2ef541c)

**Comment by eanders** [comment]
That sounds exactly like what's happening.  Try changing `PROTECTED_IDS=true` to `PROTECTED_IDS=false` in your `.env` file and restarting the rails server. That will use DB ids in the URLs instead of those hashes.

**Comment by pocketfishy** [comment]
Amazing, worked perfectly. Thank you, @eanders !
