### ISSUE TITLE
The asset "application_esbuild.js" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by pocketfishy** [greenriver/hmis-warehouse#4584]
Hi,
I recently cloned the latest stable branch and am experiencing the following error message after running bin/setup:

![image](https://github.com/user-attachments/assets/23ca6daa-4f84-4bd3-864b-ded72885a8cc)

Any help would be much appreciated!

Thank you,
Tim

**Comment by pocketfishy** [comment]
Just in case this helps anyone else, the way I fixed this was by changing 
`= javascript_include_tag 'application_esbuild', 'data-turbo-track': 'reload', defer: true`
to
`= javascript_include_tag '/assets/application_esbuild', 'data-turbo-track': 'reload', defer: true`
in hmis-warehouse/app/views/layouts/application.html.haml

**Comment by eanders** [comment]
Thanks @pocketfishy !  I think maybe calling `rails assets:precompile` and/or running `yarn` might also have fixed that.

**Comment by pocketfishy** [comment]
Thanks, @eanders. I changed the code back to the original and ran `rails assets:precompile` I can confirm that works as well!

**Comment by eanders** [comment]
That's wonderful.  If you want to open a PR to docs or `bin/setup` (or both) we'd be very appreciative!
