### ISSUE TITLE
APR Report Q19b does not count clients with chronic disability as disabled

### ISSUE THREAD

**Issue by pocketfishy** [greenriver/hmis-warehouse#4848]
Hi there,
When running the APR for the current reporting period, I found that report Q19b in the APR does not seem to be counting clients with a Chronic Disability as having a disabling condition. This can be seen below in cell G2:
![image](https://github.com/user-attachments/assets/5b87aa74-0bf2-4e08-93f5-a5010446076b)

When clicking on the link for the 4 records identified in G2 as not having a Disabling Condition, I can see that one of the clients is marked Chronic Disability = "Yes"
![image](https://github.com/user-attachments/assets/1d712a6f-e785-4d43-a971-fcb1f4202b44)

Please let me know if I can provide any other information. Hoping this is a relatively quick fix!
Thank you,

**Comment by eanders** [comment]
@pocketfishy I'm not quite sure what else to ask for, but[ looking through the code](https://github.com/greenriver/hmis-warehouse/blob/release-139/drivers/hud_apr/app/models/hud_apr/generators/shared/fy2024/question_nineteen.rb) I'm not seeing any obvious way you could end up with a `DisablingCondition` of `1` on that page.  I wonder if that column should't be treated as a boolean for display.  Can you look at the download in Excel and confirm it isn't a 99?  Ruby is a bit loose with what it considers true and false.

**Comment by pocketfishy** [comment]
Hi @eanders I'm noticing that for this client, they have DisabilityType = 7 in Disabilities.csv. This corresponds to "Chronic Health Condition":

![image](https://github.com/user-attachments/assets/05173dd5-b441-42c4-a409-979d49418f74)

**Comment by eanders** [comment]
That would be the specific disability detail, but on Enrollment they should have a value in DisablingCondition.  That's what is used to include/exclude them from the metric.

**Comment by pocketfishy** [comment]
Hi @eanders, I see what you mean. Thanks, this helped me identify an error in my code that generates the csv export. This was not an issue with Open Path. Marking as closed!
