### ISSUE TITLE
rake db:create issue

### ISSUE THREAD

**Issue by margocramer** [greenriver/hmis-warehouse#53]
I've hit a roadblock as I try to begin basic setup.

Running ```./bin/setup``` tells me that my dependencies are successfully installed. While preparing the database I get this error:

== Preparing Database ==
rake aborted!
YAML syntax error occurred while parsing /Users/margueritecramer/HMIS/hmis-warehouse/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
/Users/margueritecramer/.gem/ruby/2.3.3/gems/railties-4.2.8/lib/rails/application/configuration.rb:115:in `rescue in database_configuration'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/railties-4.2.8/lib/rails/application/configuration.rb:98:in `database_configuration'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/activerecord-4.2.8/lib/active_record/railtie.rb:41:in `block (3 levels) in <class:Railtie>'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/margueritecramer/.gem/ruby/2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/margueritecramer/.gem/ruby/2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
/Users/margueritecramer/.gem/ruby/2.3.3/gems/railties-4.2.8/lib/rails/application/configuration.rb:104:in `database_configuration'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/activerecord-4.2.8/lib/active_record/railtie.rb:41:in `block (3 levels) in <class:Railtie>'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/margueritecramer/.gem/ruby/2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/margueritecramer/.gem/ruby/2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
rake aborted!

I've tried changing the indents to spaces but that hasn't helped. The error repeats itself when I simple run ```rake db:install```

rake aborted!
YAML syntax error occurred while parsing /Users/margueritecramer/HMIS/hmis-warehouse/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
/Users/margueritecramer/.gem/ruby/2.3.3/gems/railties-4.2.8/lib/rails/application/configuration.rb:115:in `rescue in database_configuration'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/railties-4.2.8/lib/rails/application/configuration.rb:98:in `database_configuration'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/activerecord-4.2.8/lib/active_record/railtie.rb:41:in `block (3 levels) in <class:Railtie>'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/margueritecramer/.gem/ruby/2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/margueritecramer/.gem/ruby/2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
/Users/margueritecramer/.gem/ruby/2.3.3/gems/railties-4.2.8/lib/rails/application/configuration.rb:104:in `database_configuration'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/activerecord-4.2.8/lib/active_record/railtie.rb:41:in `block (3 levels) in <class:Railtie>'
/Users/margueritecramer/.gem/ruby/2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/margueritecramer/.gem/ruby/2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/margueritecramer/.gem/ruby/2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:create => db:load_config

**Comment by eanders** [comment]
@margocramer you'll need a `.env` file in the root of your install.  We don't currently have an example file in the repository, but we'll add one (along with instructions).  Here's one that will hopefully get you going in the right direction.
```
# BOSTON WAREHOUSE DEVELOPMENT ENV FILE
RAILS_ENV=development
HOSTNAME=boston-hmis.dev
PORT=80
DEFAULT_FROM="warehouse" <warehouse@example.com>
CLIENT=boston
LOGO=
TIMEZONE="Eastern Time (US & Canada)"

# Database
DATABASE_ADAPTER=postgresql
DATABASE_APP_DB=hmis_dev
DATABASE_CAS_DB=boston_ca_dev
DATABASE_HOST=localhost
DATABASE_PORT=
DATABASE_USER=
DATABASE_PASS=
DATABASE_APP_DB_TEST=boston_hmis_test

# Warehouse
WAREHOUSE_DATABASE_ADAPTER=postgresql
WAREHOUSE_DATABASE_DB=development_grda_warehouse
WAREHOUSE_DATABASE_HOST=localhost
WAREHOUSE_DATABASE_PORT=
WAREHOUSE_DATABASE_USER=
WAREHOUSE_DATABASE_PASS=
WAREHOUSE_DATABASE_DB_TEST=warehouse_test

# Health
HEALTH_DATABASE_ADAPTER=postgresql
HEALTH_DATABASE_DB=health_dev
HEALTH_DATABASE_HOST=localhost
HEALTH_DATABASE_PORT=
HEALTH_DATABASE_USER=
HEALTH_DATABASE_PASS=
HEALTH_DATABASE_DB_TEST=health_test

# Cache store
CACHE_HOST=localhost
CACHE_PORT=6379
CACHE_DB=0

# ETO API
ETO_API_USER=you@boston.gov
ETO_API_PASS=password
ETO_API_ENTERPRISE=unknown

# Exceptions
#EXCEPTION_WEBHOOK_URL=
#EXCEPTION_WEBHOOK_CHANNEL=
#EXCEPTION_WEBHOOK_ICON=

# Health SFTP
HEALTH_SFTP_HOST=
HEALTH_SFTP_PATH=
HEALTH_SFTP_USER=
HEALTH_SFTP_PASS=
HEALTH_SFTP_DESTINATION=

# Weather
WEATHER_EMAIL=
WEATHER_TOKEN=
WEATHER_DARKSKY=

# HMIS SFTP
BOSTON_ETO_SFTP_HOST=
BOSTON_ETO_SFTP_PATH=
BOSTON_ETO_SFTP_MATCH_FILE=
BOSTON_ETO_SFTP_USER=
BOSTON_ETO_SFTP_PASS=

BPHC_ETO_SFTP_HOST=
BPHC_ETO_SFTP_PATH=
BPHC_ETO_SFTP_MATCH_FILE=
BPHC_ETO_SFTP_USER=
BPHC_ETO_SFTP_PASS=
```
