### ISSUE TITLE
Admin generated by setup script has no permissions

### ISSUE THREAD

**Issue by aseroff** [greenriver/hmis-warehouse#925]
After setting up my local environment using the provided setup script, I can view the root page, as well as the Devise account links on the right, but that is all. How can I give the generated admin account permissions to explore the application and the seeded sample data?

**Comment by eanders** [comment]
@aseroff You'll need to run `Role.where(name: 'Admin').update_all(can_edit_users: true, can_edit_roles: true)`.  Thanks for pointing this out.  We'll add that bit to the seeds file.

That will give you access to the Admin dashboard where you can adjust permissions through the application's interface.

**Comment by aseroff** [comment]
Thanks @eanders, that did indeed unlock the administrative access I was expecting a seeded admin to have. Appreciate the help!

**Comment by eanders** [comment]
@aseroff, thanks for the feedback.
